DUMMY_DATA = {
    "cod": "200",
    "message": 0,
    "cnt": 40,
    "list": [
        {
            "dt": 1689973200,
            "main": {
                "temp": 301.05,
                "feels_like": 301.08,
                "temp_min": 300.88,
                "temp_max": 301.05,
                "pressure": 1013,
                "sea_level": 1013,
                "grnd_level": 1009,
                "humidity": 45,
                "temp_kf": 0.17,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 3.8, "deg": 309, "gust": 3.7},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-21 21:00:00",
        },
        {
            "dt": 1689984000,
            "main": {
                "temp": 300.08,
                "feels_like": 299.96,
                "temp_min": 299.56,
                "temp_max": 300.08,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1008,
                "humidity": 40,
                "temp_kf": 0.52,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 3.79, "deg": 286, "gust": 4.41},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-22 00:00:00",
        },
        {
            "dt": 1689994800,
            "main": {
                "temp": 290.84,
                "feels_like": 290.34,
                "temp_min": 290.84,
                "temp_max": 290.84,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1008,
                "humidity": 64,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02d",
                }
            ],
            "clouds": {"all": 13},
            "wind": {"speed": 2.96, "deg": 248, "gust": 3.22},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-22 03:00:00",
        },
        {
            "dt": 1690005600,
            "main": {
                "temp": 286.67,
                "feels_like": 286.14,
                "temp_min": 286.67,
                "temp_max": 286.67,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1008,
                "humidity": 79,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 25},
            "wind": {"speed": 2.94, "deg": 229, "gust": 2.6},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-22 06:00:00",
        },
        {
            "dt": 1690016400,
            "main": {
                "temp": 286.73,
                "feels_like": 286.23,
                "temp_min": 286.73,
                "temp_max": 286.73,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1007,
                "humidity": 80,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 76},
            "wind": {"speed": 2.48, "deg": 227, "gust": 2.21},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-22 09:00:00",
        },
        {
            "dt": 1690027200,
            "main": {
                "temp": 286.24,
                "feels_like": 285.67,
                "temp_min": 286.24,
                "temp_max": 286.24,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1006,
                "humidity": 79,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 87},
            "wind": {"speed": 2.16, "deg": 233, "gust": 2},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-22 12:00:00",
        },
        {
            "dt": 1690038000,
            "main": {
                "temp": 289.92,
                "feels_like": 289.32,
                "temp_min": 289.92,
                "temp_max": 289.92,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1007,
                "humidity": 64,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 53},
            "wind": {"speed": 1.39, "deg": 240, "gust": 1.45},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-22 15:00:00",
        },
        {
            "dt": 1690048800,
            "main": {
                "temp": 297.17,
                "feels_like": 296.75,
                "temp_min": 297.17,
                "temp_max": 297.17,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1007,
                "humidity": 43,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 59},
            "wind": {"speed": 2.33, "deg": 322, "gust": 1.64},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-22 18:00:00",
        },
        {
            "dt": 1690059600,
            "main": {
                "temp": 300.93,
                "feels_like": 300.33,
                "temp_min": 300.93,
                "temp_max": 300.93,
                "pressure": 1009,
                "sea_level": 1009,
                "grnd_level": 1006,
                "humidity": 35,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 7},
            "wind": {"speed": 3.79, "deg": 306, "gust": 3.64},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-22 21:00:00",
        },
        {
            "dt": 1690070400,
            "main": {
                "temp": 298.67,
                "feels_like": 298.27,
                "temp_min": 298.67,
                "temp_max": 298.67,
                "pressure": 1009,
                "sea_level": 1009,
                "grnd_level": 1005,
                "humidity": 38,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "clouds": {"all": 44},
            "wind": {"speed": 3.68, "deg": 278, "gust": 4},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-23 00:00:00",
        },
        {
            "dt": 1690081200,
            "main": {
                "temp": 290.27,
                "feels_like": 289.89,
                "temp_min": 290.27,
                "temp_max": 290.27,
                "pressure": 1009,
                "sea_level": 1009,
                "grnd_level": 1006,
                "humidity": 71,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 93},
            "wind": {"speed": 3.31, "deg": 240, "gust": 3.4},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-23 03:00:00",
        },
        {
            "dt": 1690092000,
            "main": {
                "temp": 287.77,
                "feels_like": 287.38,
                "temp_min": 287.77,
                "temp_max": 287.77,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1007,
                "humidity": 80,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 70},
            "wind": {"speed": 2.99, "deg": 228, "gust": 2.8},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-23 06:00:00",
        },
        {
            "dt": 1690102800,
            "main": {
                "temp": 286.59,
                "feels_like": 286.24,
                "temp_min": 286.59,
                "temp_max": 286.59,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1007,
                "humidity": 86,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 2.74, "deg": 230, "gust": 2.42},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-23 09:00:00",
        },
        {
            "dt": 1690113600,
            "main": {
                "temp": 286.11,
                "feels_like": 285.71,
                "temp_min": 286.11,
                "temp_max": 286.11,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1007,
                "humidity": 86,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 90},
            "wind": {"speed": 2.69, "deg": 232, "gust": 2.62},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-23 12:00:00",
        },
        {
            "dt": 1690124400,
            "main": {
                "temp": 288.28,
                "feels_like": 287.86,
                "temp_min": 288.28,
                "temp_max": 288.28,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1008,
                "humidity": 77,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 99},
            "wind": {"speed": 2.47, "deg": 237, "gust": 2.71},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-23 15:00:00",
        },
        {
            "dt": 1690135200,
            "main": {
                "temp": 294.01,
                "feels_like": 293.59,
                "temp_min": 294.01,
                "temp_max": 294.01,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1009,
                "humidity": 55,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 91},
            "wind": {"speed": 2.99, "deg": 279, "gust": 3.2},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-23 18:00:00",
        },
        {
            "dt": 1690146000,
            "main": {
                "temp": 296.97,
                "feels_like": 296.61,
                "temp_min": 296.97,
                "temp_max": 296.97,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1008,
                "humidity": 46,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 87},
            "wind": {"speed": 3.44, "deg": 282, "gust": 3.92},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-23 21:00:00",
        },
        {
            "dt": 1690156800,
            "main": {
                "temp": 294.89,
                "feels_like": 294.4,
                "temp_min": 294.89,
                "temp_max": 294.89,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1009,
                "humidity": 49,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "clouds": {"all": 45},
            "wind": {"speed": 3.53, "deg": 278, "gust": 4.72},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-24 00:00:00",
        },
        {
            "dt": 1690167600,
            "main": {
                "temp": 289.41,
                "feels_like": 288.84,
                "temp_min": 289.41,
                "temp_max": 289.41,
                "pressure": 1013,
                "sea_level": 1013,
                "grnd_level": 1009,
                "humidity": 67,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02d",
                }
            ],
            "clouds": {"all": 17},
            "wind": {"speed": 3.15, "deg": 243, "gust": 4.1},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-24 03:00:00",
        },
        {
            "dt": 1690178400,
            "main": {
                "temp": 285.63,
                "feels_like": 285.21,
                "temp_min": 285.63,
                "temp_max": 285.63,
                "pressure": 1014,
                "sea_level": 1014,
                "grnd_level": 1011,
                "humidity": 87,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02n",
                }
            ],
            "clouds": {"all": 12},
            "wind": {"speed": 3.03, "deg": 223, "gust": 3.5},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-24 06:00:00",
        },
        {
            "dt": 1690189200,
            "main": {
                "temp": 285.3,
                "feels_like": 284.95,
                "temp_min": 285.3,
                "temp_max": 285.3,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 1011,
                "humidity": 91,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02n",
                }
            ],
            "clouds": {"all": 15},
            "wind": {"speed": 2.74, "deg": 223, "gust": 2.91},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-24 09:00:00",
        },
        {
            "dt": 1690200000,
            "main": {
                "temp": 285.6,
                "feels_like": 285.3,
                "temp_min": 285.6,
                "temp_max": 285.6,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 1012,
                "humidity": 92,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 44},
            "wind": {"speed": 2.39, "deg": 224, "gust": 2.2},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-24 12:00:00",
        },
        {
            "dt": 1690210800,
            "main": {
                "temp": 287.87,
                "feels_like": 287.54,
                "temp_min": 287.87,
                "temp_max": 287.87,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 1013,
                "humidity": 82,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 99},
            "wind": {"speed": 2.21, "deg": 237, "gust": 2.61},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-24 15:00:00",
        },
        {
            "dt": 1690221600,
            "main": {
                "temp": 294.59,
                "feels_like": 294.04,
                "temp_min": 294.59,
                "temp_max": 294.59,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 1013,
                "humidity": 48,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 93},
            "wind": {"speed": 3.29, "deg": 295, "gust": 4.31},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-24 18:00:00",
        },
        {
            "dt": 1690232400,
            "main": {
                "temp": 296.84,
                "feels_like": 296.28,
                "temp_min": 296.84,
                "temp_max": 296.84,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 1013,
                "humidity": 39,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 69},
            "wind": {"speed": 4.1, "deg": 298, "gust": 5.6},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-24 21:00:00",
        },
        {
            "dt": 1690243200,
            "main": {
                "temp": 295.11,
                "feels_like": 294.51,
                "temp_min": 295.11,
                "temp_max": 295.11,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 1013,
                "humidity": 44,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 68},
            "wind": {"speed": 4.36, "deg": 284, "gust": 7.32},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-25 00:00:00",
        },
        {
            "dt": 1690254000,
            "main": {
                "temp": 290.43,
                "feels_like": 290.02,
                "temp_min": 290.43,
                "temp_max": 290.43,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 1013,
                "humidity": 69,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02d",
                }
            ],
            "clouds": {"all": 11},
            "wind": {"speed": 3.22, "deg": 255, "gust": 5.2},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-25 03:00:00",
        },
        {
            "dt": 1690264800,
            "main": {
                "temp": 286.85,
                "feels_like": 286.57,
                "temp_min": 286.85,
                "temp_max": 286.85,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 1013,
                "humidity": 88,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 10},
            "wind": {"speed": 3.24, "deg": 221, "gust": 3.64},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-25 06:00:00",
        },
        {
            "dt": 1690275600,
            "main": {
                "temp": 286.77,
                "feels_like": 286.59,
                "temp_min": 286.77,
                "temp_max": 286.77,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 1013,
                "humidity": 92,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 44},
            "wind": {"speed": 2.76, "deg": 227, "gust": 3.03},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-25 09:00:00",
        },
        {
            "dt": 1690286400,
            "main": {
                "temp": 286.11,
                "feels_like": 285.92,
                "temp_min": 286.11,
                "temp_max": 286.11,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 1012,
                "humidity": 94,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 48},
            "wind": {"speed": 2.47, "deg": 218, "gust": 2.42},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-25 12:00:00",
        },
        {
            "dt": 1690297200,
            "main": {
                "temp": 289.01,
                "feels_like": 288.74,
                "temp_min": 289.01,
                "temp_max": 289.01,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 1013,
                "humidity": 80,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02d",
                }
            ],
            "clouds": {"all": 11},
            "wind": {"speed": 1.83, "deg": 235, "gust": 2.11},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-25 15:00:00",
        },
        {
            "dt": 1690308000,
            "main": {
                "temp": 295.81,
                "feels_like": 295.49,
                "temp_min": 295.81,
                "temp_max": 295.81,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 1013,
                "humidity": 52,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 7},
            "wind": {"speed": 2.53, "deg": 311, "gust": 2.61},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-25 18:00:00",
        },
        {
            "dt": 1690318800,
            "main": {
                "temp": 298.68,
                "feels_like": 298.44,
                "temp_min": 298.68,
                "temp_max": 298.68,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 1012,
                "humidity": 44,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 1},
            "wind": {"speed": 3.95, "deg": 295, "gust": 4.43},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-25 21:00:00",
        },
        {
            "dt": 1690329600,
            "main": {
                "temp": 294.73,
                "feels_like": 294.54,
                "temp_min": 294.73,
                "temp_max": 294.73,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 1011,
                "humidity": 61,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 1},
            "wind": {"speed": 4.25, "deg": 278, "gust": 6.1},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-26 00:00:00",
        },
        {
            "dt": 1690340400,
            "main": {
                "temp": 289.2,
                "feels_like": 289.08,
                "temp_min": 289.2,
                "temp_max": 289.2,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 1012,
                "humidity": 85,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 1},
            "wind": {"speed": 2.85, "deg": 255, "gust": 3.81},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-26 03:00:00",
        },
        {
            "dt": 1690351200,
            "main": {
                "temp": 286.79,
                "feels_like": 286.56,
                "temp_min": 286.79,
                "temp_max": 286.79,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 1012,
                "humidity": 90,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 48},
            "wind": {"speed": 2.21, "deg": 239, "gust": 2.33},
            "visibility": 3222,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-26 06:00:00",
        },
        {
            "dt": 1690362000,
            "main": {
                "temp": 285.6,
                "feels_like": 285.28,
                "temp_min": 285.6,
                "temp_max": 285.6,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 1012,
                "humidity": 91,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 61},
            "wind": {"speed": 2.44, "deg": 238, "gust": 2.53},
            "visibility": 4272,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-26 09:00:00",
        },
        {
            "dt": 1690372800,
            "main": {
                "temp": 285.21,
                "feels_like": 284.9,
                "temp_min": 285.21,
                "temp_max": 285.21,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 1011,
                "humidity": 93,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 55},
            "wind": {"speed": 2.2, "deg": 239, "gust": 2.43},
            "visibility": 5297,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-07-26 12:00:00",
        },
        {
            "dt": 1690383600,
            "main": {
                "temp": 286.98,
                "feels_like": 286.64,
                "temp_min": 286.98,
                "temp_max": 286.98,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 1012,
                "humidity": 85,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "clouds": {"all": 40},
            "wind": {"speed": 2.09, "deg": 243, "gust": 2.52},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-26 15:00:00",
        },
        {
            "dt": 1690394400,
            "main": {
                "temp": 292.74,
                "feels_like": 292.24,
                "temp_min": 292.74,
                "temp_max": 292.74,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 1012,
                "humidity": 57,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02d",
                }
            ],
            "clouds": {"all": 21},
            "wind": {"speed": 2.97, "deg": 288, "gust": 2.9},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-07-26 18:00:00",
        },
    ],
    "city": {
        "id": 0,
        "name": "Mountain View",
        "coord": {"lat": 37.3855, "lon": -122.088},
        "country": "US",
        "population": 0,
        "timezone": -25200,
        "sunrise": 1689944617,
        "sunset": 1689996331,
    },
}